### ISSUE TITLE
Daydream controller JS emulator

### ISSUE THREAD

**Issue by FluorescentHallucinogen** [mrdoob/daydream-controller.js#8]
First of all, thank you so much for your work, @mrdoob!

If I understood correctly, this is a Daydream controller receiver written in JavaScript using Web Bluetooth API.

Is it possible to write Daydream controller sender (emulator) completely in JavaScript using Web Bluetooth API and Motion Sensors APIs based on Generic Sensor API (https://www.chromestatus.com/feature/5698781827825664) that allows to use a device with relevant sensors (e.g. Android smartphone with gyroscope) in place of a Daydream controller?

Now I'm using native Daydream controller Android app: https://developers.google.com/vr/daydream/controller-emulator.

**Comment by mrdoob** [comment]
I don't think the WebBluetooth API allows this.
