### ISSUE TITLE
It still work?

### ISSUE THREAD

**Issue by mrsions** [mrdoob/daydream-controller.js#9]
My phone is not working this project. (https://mrdoob.github.io/daydream-controller.js/)

Galaxy S10+ (it is not support daydream platform)
and Daydream Controller.

and i checked controller from "BLE Scanner"

Hardware version: 0005.0003
Firmware version 1.3.5
Software version 825769af

It it not work normal?

**Comment by mrdoob** [comment]
Yeah, I think this stopped working in a firmware update at some point last year 😕

**Comment by jadware** [comment]
I believe that the controller does not transmit the values until a secure BLE connection has been made (the bonding process).  I'm not sure how to do that through web bluetooth, if it's even possible.

**Comment by bigrig2212** [comment]
Anyone have an update this? No one has luck making connection anymore?

**Comment by mrdoob** [comment]
Unfortunately not. And I'm going to archive this repo.
